version: '3'
# docker-composeの書式のバージョンを指定します。(原則、最新を指定する)

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
  # =========ローカルと本番切り替え===========
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb -e production"
  # ======================================
    volumes:
      - .:/fodeli_online/
      - public-data:/fodeli_online/public
      - tmp-data:/fodeli_online/tmp
      - log-data:/fodeli_online/log
    tty: true
    stdin_open: true
    environment:
      - "SELENIUM_DRIVER_URL=http://chrome:4444/wd/hub"
    networks:
      - fodeli-online-network
  # =========ローカルと本番切り替え===========
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    networks:
      - fodeli-online-network
  # ======================================

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - public-data:/fodeli_online/public
      - tmp-data:/fodeli_online/tmp
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - fodeli-online-network

# =========ローカルと本番切り替え===========
  chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - fodeli-online-network
# ======================================

volumes:
  db-data:
  public-data:
  tmp-data:
  log-data:

networks:
  fodeli-online-network:
    external: true